### ISSUE TITLE
Working together with jqueries datatables

### ISSUE THREAD

**Issue by tefod-zz** [jmalarcon/jquery.pan#3]
Hi,
hence there is no issue, I hope its fine, when I ask my question in the issue tracker.

I have some issue together with datatables and the responsive child-items, respectively sub-rows.

Any ideas. I appreciate any help.
Thanks...

Edit: has been kindly answered by kthorngren in the datatables forum. The hidden child details arent in the dom with activated responsive. 
https://datatables.net/reference/event/responsive-display

**Comment by jmalarcon** [comment]
Hi,

Unfortunately y don't use DataTables, so I couldn't have helped you this time, but I'm glad that you have solved your issue 😊 

Thanks for posting the link to the solution.

Best regards.

**Comment by tefod-zz** [comment]
Hey Jose,
thank you too for taking time to comment the inquiry :)
Great fork by the way..

Regards,
Tefo
